### ISSUE TITLE
cmake时出现了问题

### ISSUE THREAD

**Issue by leeztt** [Alibaba-Gemini-Lab/OpenCheetah#11]
您好，当我cmake时提示SEAL包找不到，和 #6 类似，OpenCheetah/build/deps/SEAL目录下没有SEALConfig.cmake文件，但是OpenCheetah/deps/SEAL下不为空，请问这应该怎么解决？
![20220629213256](https://user-images.githubusercontent.com/108344557/176450689-ceca2c7b-8629-4f5c-982d-3d44cf76fe9c.png)

**Comment by fionser** [comment]
请使用 `scripts` 目录下的脚本进行编译。因为在里面我们设置了 CMAKE_PREFIX_PATH 的路径指向 `build/`

**Comment by leeztt** [comment]
ok，thanks！😀
