### ISSUE TITLE
 Millionaires' issue

### ISSUE THREAD

**Issue by nyc-crypto** [Alibaba-Gemini-Lab/OpenCheetah#12]
m=4时，通信量为11L，但16选1的OT的通信复杂度至少为16L，请教下怎么得到总的通信量为11L

**Comment by zicofish** [comment]
@nyc-crypto 16选1的OT中消息长度只有 1 比特，所以它的通信量是 16，不是16L。表中的 11L 是综合了整个 millionaire 协议的通信开销给出的一个上界，包括了 16 选1 OT 的开销和 AND gate 的开销

**Comment by nyc-crypto** [comment]
叶子节点的开销是（2^m+log(2^m)）* L/m*2，AND运算的开销是4*（L/m-1）*2，这样估算的话，m=1和m=4的上届与论文不太一致呢

**Comment by zicofish** [comment]
@nyc-crypto 这里面涉及的变量太多了，你得去看 cryptflow2 里面的那个复杂度估计，然后把 L 和 m 取一些值来消掉某些变量，才能得到这个很粗略的 11L 估计（他们论文里也是需要取 L=32，m=4 才能给出个简单点的估算式子，不然那个准确的式子写出来太复杂，给不了别人“到底通信量是多少”的印象）。比如，L=32，m=4，那么q=L/m=8，按cryptflow2的那个复杂度分析，整个协议需要：

1次 (1-of-16) OT_1  -->  小于 L bit
(q-1) 次 (1-of-16) OT_2  -->  7 * (16 * 2 + 4)  --> 小于  8L bit
(2q-1-logq) 个 AND gate  -->  (2q-1-logq) * 4  -->  小于 2L bit

总共小于 11L bit。

再次强调一下，这个复杂度估计是很粗略的，只是为了给大家一个大致的开销印象，如果 L 取别的值（比如64），这个估计是需要调整的，但是不会有数量级的差别。这个简化的式子方便对比 cheetah 方案和 cryptflow2 方案，如果把完全精确的那个复杂度放出来，很难直观看到具体对比情况的。
