### ISSUE TITLE
test or demo

### ISSUE THREAD

**Issue by oahcnauygnid** [Alibaba-Gemini-Lab/OpenCheetah#17]
你好！请问如果我想搭一个简单的模型的话，我应该怎么做？1）我看到在SCI里有一些test，我按照相应的结构来调用并指明USE_CHEETAH？2）或者我看到cheetah_api相关的文件，应该使用这里的函数吗？此外，我还想问下SCI里的这些test是否已经经由cheetah改过了，以及是否有构建简单网络的demo，而不是生成的几千行代码来构建？

**Comment by fionser** [comment]
- `SCI`  目录下的 `test` 文件并没有全部经过 cheetah “改造“
-  实际上目前 Cheetah 代码可以认为是 SCI 的一个 backend. 具体生成的前端代码 (如 `network/`) 应该是完全兼容 SCI repo 库的
