### ISSUE TITLE
Windows系统上Build Dependency报错

### ISSUE THREAD

**Issue by HelmetOff** [Alibaba-Gemini-Lab/OpenCheetah#18]
你好，我遇到的问题与 #4 一样，区别我是在windows环境，请问要怎么解决？

HEAD is now at 44b1dde Fix silent failure in CPU seed generation (#156)
M       CMakeLists.txt
M       emp-tool/emp-tool.h
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file CMakeLists.txt.rej
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file emp-tool/emp-tool.h.rej
-- Platform: AMD64
-- Build type: Release
-- CXX Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc /DWIN32 /D_WINDOWS /W3 -pthread -Wall -funroll-loops -Wno-ignored-attributes -Wno-unused-result -march=native -maes -mrdseed -std=c++11 -O3
-- Performing Test RDSEED_RUN_RESULT
-- Performing Test RDSEED_RUN_RESULT - Failed
-- Source of Randomness: random_device
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/yckj4361/CLionProjects/OpenCheetah2/build/deps/emp-tool
make: *** No rule to make target 'install'.  Stop.
HEAD is now at 7f3d4f0 fix the bug #67 raised by @themighty1 (#68)
CMake Error at CMakeLists.txt:6 (include):
  include could not find requested file:

    CMAKE_FOLDER-NOTFOUND/cmake/emp-base.cmake

CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findemp-tool.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "emp-tool",
  but CMake did not find one.

  Could not find a package configuration file provided by "emp-tool" with any
  of the following names:

    emp-toolConfig.cmake
    emp-tool-config.cmake

  Add the installation prefix of "emp-tool" to CMAKE_PREFIX_PATH or set
  "emp-tool_DIR" to a directory containing one of the above files.  If
  "emp-tool" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by fionser** [comment]
抱歉，目前脚本不支持 windows 环境的编译。
