### ISSUE TITLE
hexl与SEAL的版本冲突

### ISSUE THREAD

**Issue by cmZoO** [Alibaba-Gemini-Lab/OpenCheetah#2]
build-deps.sh中拉下来的hexl是1.2.2版本的，SEAL是3.7.2版本的。但是在SEAL3.7.2版本的[CMakeList](https://github.com/microsoft/SEAL/blob/79234726053c45eede688400aa219fdec0810bd8/CMakeLists.txt)的226行中，约束了hexl的版本为1.2.3。

**Comment by vincehong** [comment]
This is by design. [SEAL.patch](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/blob/main/patch/SEAL.patch) is used to modify that.
