### ISSUE TITLE
请问目前仅支持BFV加密方案吗?

### ISSUE THREAD

**Issue by yuntao-wei** [Alibaba-Gemini-Lab/OpenCheetah#21]
![image](https://user-images.githubusercontent.com/47071642/206857609-eb6c31b8-1e55-4ce6-9c5d-beb0fb58d3eb.png)
注意到有关encode的代码似乎不支持ckks等其他加密方案？

**Comment by fionser** [comment]
目前只支持 bfv; 主要原因是因为 ckks 没办法做 noise flooding; 这要导致用 ckks 去实现的 cheetah 没办法做到可证安全。
