### ISSUE TITLE
是否支持conv1d?

### ISSUE THREAD

**Issue by oahcnauygnid** [Alibaba-Gemini-Lab/OpenCheetah#23]
我想要使用conv1d，但没有找到相应的函数，当我想借用conv2d来实现conv1d时，即在数据和卷积核上均增加一个维度，shape(n)->shape(n,1)，出现关于slice的报错[OpenCheetah/include/gemini/cheetah/sliced_3d_tensor.h:152] Conv2DSliceHelper: invalid paddings，想问下是否能够解决？

**Comment by fionser** [comment]
- try with stride=1.
- 目前的 Code 我没有考虑到 stride_x, stride_y 是不同的情况。所以用 conv2d 去做 conv1d 的话；可以试试 stride=1 ；这样 slice tensor 的部分应该也是对的。
