### ISSUE TITLE
Why Cheetah uses Ferret for OT, not Sliver? 

### ISSUE THREAD

**Issue by oahcnauygnid** [Alibaba-Gemini-Lab/OpenCheetah#25]
Why Cheetah uses Ferret-OTe, not Sliver-OTe? The latter seems more efficient.

**Comment by fionser** [comment]
Because deploying Ferret (ie emp-ot) into SCI is way more easier than using Peter's libOTe library (ie Silver) since SCI itself uses emp-ot too. 

Also, Silver depends on a very new assumption for security.

**Comment by oahcnauygnid** [comment]
Thanks!
