### ISSUE TITLE
How to support new models?

### ISSUE THREAD

**Issue by hobbitlzy** [Alibaba-Gemini-Lab/OpenCheetah#27]
Under the directory `/networks`, the model definition seems to be auto-generated. How can I add new models?😀

**Comment by fionser** [comment]
The models are generated from `EzPC` project. 
Checkout [EzPC/Athos](https://github.com/mpc-msri/EzPC/tree/master/Athos)

**Comment by hobbitlzy** [comment]
Okay, thanks for the help.
