### ISSUE TITLE
Regaring log file

### ISSUE THREAD

**Issue by MEAMITBHOWMICK** [Alibaba-Gemini-Lab/OpenCheetah#28]
After running the local demo it's showing that check in the log file (cheetah-sqnet_server.log)
for more details but I can't find any log file where it is created.

Another question I would like to ask what is the input for the local demo program.

**Comment by fionser** [comment]
opps: it seems I have comment out the re-direction in the script files [for example](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/blob/main/scripts/run-client.sh#L21)
So all the logs are written to the standard output (ie console)
