### ISSUE TITLE
关于openssl

### ISSUE THREAD

**Issue by TuoniTuoni** [Alibaba-Gemini-Lab/OpenCheetah#3]
新手小白，麻烦问下-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl是指定openssl的安装位置吗，我本地没有这个位置，但是也编译通过了，是不是也没有错误？openssl的作用是什么，谢谢

**Comment by fionser** [comment]
OpenSSL is used by emp-tool (e.g., ECC group operations)

**Comment by TuoniTuoni** [comment]
> OpenSSL is used by emp-tool (e.g., ECC group operations)

谢谢，-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl，请问这个路径是什么，openssl的头文件位置还是静态库（动态库）位置？

**Comment by fionser** [comment]
We expect the header directory `${OPENSSL_ROOT_DIR}/include/openssl` and the *.a files under `${OPENSSL_ROOT_DIR}/lib/ `

Checkout the Cmake FindOpenSSL command [here](https://cmake.org/cmake/help/v3.6/module/FindOpenSSL.html)

**Comment by TuoniTuoni** [comment]
> We expect the header directory `${OPENSSL_ROOT_DIR}/include/openssl` and the *.a files under `${OPENSSL_ROOT_DIR}/lib/ `
> 
> Checkout the Cmake FindOpenSSL command [here](https://cmake.org/cmake/help/v3.6/module/FindOpenSSL.html)

tks
