### ISSUE TITLE
论文中的extract和remask操作

### ISSUE THREAD

**Issue by han-hs16** [Alibaba-Gemini-Lab/OpenCheetah#30]
论文中是利用extract和remask完成FC和Conv等线性层的有效输出系数的搜集，但代码中的实现利用removeUnusedCoeffs去除无用系数，并解密得到输出系数。

我对extract和remask比较感兴趣，论文中是参考了Efficient Homomorphic Conversion Between (Ring) LWE Ciphertexts的工作，但我没找到这篇论文的开源实现，想请问下，cheetah是否之前实现了extract(以及LWEs到RLWE的重新打包)，有的话可否分享下代码？以及Efficient Homomorphic Conversion Between (Ring) LWE Ciphertexts中只介绍了LWEs到RLWE的技术(也就是重新打包)，extract部分是利用了什么技术呢？

提前感谢您的回复！

**Comment by fionser** [comment]
- Extract a LWE from RLWE under the X^N + 1 (N is 2-power) ring is a trivial task.
   * For example, `RLWE(m(X))` is given as two polynomial `(b(X), a(X))` which is decrypted as `b(X) + a(X) * s(X) mod X^N + 1` 
   *  To extract the k-th coefficient of this RLWE to obtain `LWE(m_k)` (i.e, LWE encryption of the k-th coefficient) is simply doing coefficient re-ordering.
       Suppose `LWE(m_k)` is given  as `(c, \vec{d})` then we have `c = b[k]` (ie the k-th coefficient of b(X)) and 
       `\vec{d}  = [a[k], a[k-1], ...., a[0], -a[N-1], -a[N-2], ...., -a[k+1]]` (ie. reverse the first k coefficients of a(X) and reverse-then-flip-sign of the remaining N-k coefficients 
* This is simply a reverse computation of Section 3.3 in _Efficient Homomorphic Conversion Between (Ring) LWE Ciphertexts_ without using the Trace function.
* For the RLWE-to-LWE extraction implementation, check out [here](https://code.alipay.com/secretflow/ppu/blob/master/libspu/mpc/cheetah/rlwe/lwe_ct.cc#L42)
* We have plan to open the PackLWEs codes in the near future (see our [GBDT paper](https://eprint.iacr.org/2023/527))

**Comment by han-hs16** [comment]
感谢您及时的回复，解决了我的疑惑，期待后续的开源项目！
