### ISSUE TITLE
怎么读懂代码实现的细节？

### ISSUE THREAD

**Issue by YefanWu** [Alibaba-Gemini-Lab/OpenCheetah#31]
我阅读了Cheetah的论文，并理解了这些MPC协议的思想和技术，但我对理解这些代码的复现细节依然毫无头绪。
我的问题包括：
1）如果我想用Cheetah在其他的CNN模型上进行安全推理，应该从哪里入手改动代码？
2）如果我想调试Cheetah的线性层和非线性层协议，应该从哪里入手？

**Comment by fionser** [comment]
- 当前的代码是基于微软的 EzPC 库（特别是 SCI)；我们只是做了一个 SCI 的后端。
    - 譬如 [这里](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/blob/main/SCI/src/library_fixed_uniform_cheetah.cpp)；这个 cpp 文件就是实现了 SCI的相同的API；但是具体 协议是替换为 Cheetah 的。
    - 所以只是想用其他的CNN 模型；可以不需要改 这些 CPP 代码；只需要看懂 EzPC 的库；如何输出 [这里的](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/tree/main/networks) 中间层代码即可
