### ISSUE TITLE
Question about removeUnusedCoeffs

### ISSUE THREAD

**Issue by jqxue1999** [Alibaba-Gemini-Lab/OpenCheetah#35]
Hi,

**removeUnusedCoeffs** is the function to remove the un-used plaintext polynomial coefficients by masking the ciphertext. Honestly, I cannot understand it princeple. Could you help me how did you do that? Masking the ciphertext to operate its corresponing plaintext?

Thanks in advance for your reply!

**Comment by fionser** [comment]
- checkout https://github.com/Alibaba-Gemini-Lab/OpenCheetah/issues/34
- Basically, to exact multiple LWE ciphertexts from a single RLWE ciphertext, the LWE ciphertexts will share a common vector part (but in a different order of coefficients)

**Comment by jqxue1999** [comment]
Thanks for your reply!

我观察到在您的removeUnusedCoeffs 实现中，您通过修改密文对应系数为0来实现修改明文上对应位置系数。但是我尝试了一下：

明文多项式4x^3 + 3x^2 + 2x^1 + 1，转换为密文后，修改密文对应x^2的系数，解密后发现明文上的3x^2 并没有变成0x^2，而是变成了1Ax^2。

您能够告诉我哪里出现了问题吗？还是我的理解有误。因为我正好需要一个函数通过操作RLWE密文来实现修改明文的某些系数为0.

![image](https://github.com/Alibaba-Gemini-Lab/OpenCheetah/assets/55708777/9cfe6985-1169-4137-b9cd-7571078d2ec0)

**Comment by fionser** [comment]
我们来观察 RLWE 的解密函数`ct = (b(x), a(x))`, 
Dec(ct) = b(x) + a(x) * s(x)
如果我们把 b(x) 中某些系数置为 0 （其实是可以置为其他的随机值；置0 是为了等价于传 LWE）
那么解密 b(x) + a(x) * s(x) 的之后；被置0 的位置相当于没有被完全解密。

**Comment by fionser** [comment]
“因为我正好需要一个函数通过操作RLWE密文来实现修改明文的某些系数为0”
需要更加复杂的计算；

**Comment by jqxue1999** [comment]
感谢您的回答，解决了我的疑问！
