### ISSUE TITLE
关于测量在线阶段的开销

### ISSUE THREAD

**Issue by biexin666666** [Alibaba-Gemini-Lab/OpenCheetah#36]
您好。
我想请问一下，实验最后显示的总通信量和总计算量是总的开销（在线+离线）还是单纯是在线阶段的开销。看论文里好像说时间是总时间，通信量去除了离线阶段对OT等预处理的通信。
如果我只想测量在线阶段的通信量和计算时间，有什么好方法吗。把最后显示的每一个部分（ReLU、Conv等）的时间和通信加起来是在线阶段的总开销吗。

**Comment by vincehong** [comment]
cheetah因为没有做triple，而是直接乘，所以不分在线离线的，目前都是总开销，没法分开测量。

**Comment by biexin666666** [comment]
好的，明白了，感谢
