### ISSUE TITLE
关于Building Dependencies

### ISSUE THREAD

**Issue by lsm000** [Alibaba-Gemini-Lab/OpenCheetah#4]
您好，我想问一下，我装了一台全新的虚拟机，下载了您的代码并安装好requirements中的内容后，运行bash scripts/build-deps.sh后出错了，最后的错误提示是emp-ot seems absent in /home/lsm/OpenCheetah/build/include/, please re-run scripts/build-deps.sh。
并且在刚开始就出现以下错误提示：
-- Build files have been written to: /home/lsm/OpenCheetah/deps/emp-tool
make: *** 没有规则可制作目标“install”。 停止。
HEAD 目前位于 7f3d4f0 fix the bug #67 raised by @themighty1 (#68)
CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CMAKE_FOLDER-NOTFOUND/cmake/emp-base.cmake

CMake Error at CMakeLists.txt:8 (find_package):
  By not providing "Findemp-tool.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "emp-tool", but CMake did not find one.

  Could not find a package configuration file provided by "emp-tool" with any of the following names:

    emp-toolConfig.cmake
    emp-tool-config.cmake

  Add the installation prefix of "emp-tool" to CMAKE_PREFIX_PATH or set "emp-tool_DIR" to a directory containing one of the above files.  If "emp-tool" provides a separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/lsm/OpenCheetah/build/deps/emp-ot/CMakeFiles/CMakeOutput.log".
make: *** 没有规则可制作目标“install”。 停止。
HEAD 目前位于 1f05f51 Update to version 3.3.3
-- Standard libraries to link to explicitly: none
-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find SUPERLU (missing: SUPERLU_INCLUDES SUPERLU_LIBRARIES SUPERLU_VERSION_OK) 
-- Could NOT find PASTIX (missing: PASTIX_INCLUDES PASTIX_LIBRARIES) 
-- Could NOT find SCOTCH (missing: SCOTCH_INCLUDES SCOTCH_LIBRARIES) 
-- Could NOT find METIS (missing: METIS_INCLUDES METIS_LIBRARIES) 
-- Found unsuitable Qt version "" from NOTFOUND
-- Could NOT find Boost (missing: Boost_INCLUDE_DIR) 
-- Could NOT find XSMM (missing: LIBXSMM) 
-- Could NOT find GOOGLEHASH (missing: GOOGLEHASH_INCLUDES GOOGLEHASH_COMPILE) 
-- Could NOT find ADOLC (missing: ADOLC_INCLUDES ADOLC_LIBRARIES) 
-- Could NOT find MPFR (missing: MPFR_INCLUDES MPFR_LIBRARIES MPFR_VERSION_OK) (Required is at least version "2.3.0")
-- Could NOT find GMP (missing: GMP_INCLUDES GMP_LIBRARIES) 
-- Could NOT find FFTW (missing: FFTW_INCLUDES FFTW_LIBRARIES) 
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)  CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
-- Found unsuitable Qt version "" from NOTFOUND
-- Qt4 not found, so disabling the mandelbrot and opengl demos
-- Could NOT find SUPERLU (missing: SUPERLU_INCLUDES SUPERLU_LIBRARIES SUPERLU_VERSION_OK) 
-- Could NOT find PASTIX (missing: PASTIX_INCLUDES PASTIX_LIBRARIES) 
-- Could NOT find SCOTCH (missing: SCOTCH_INCLUDES SCOTCH_LIBRARIES) 
-- Could NOT find METIS (missing: METIS_INCLUDES METIS_LIBRARIES) 

请问这是为什么呢？是我少安装了什么东西吗？

**Comment by fionser** [comment]
The dependencies are all  taken from Github, so make sure that your machine can connect to Github :).
Checkout the `deps/` dir and see whether all the dependencies are there.

**Comment by lsm000** [comment]
您好，我的虚拟机可以连接GitHub。我的OpenCheetah/deps中包含eigen、emp-ot、emp-tool、hexl、SEAL和zstd这六个文件夹。（抱歉，我不太会用GitHub，不知道该如何上传图片）

**Comment by fionser** [comment]
>>
     错误提示是emp-ot seems absent in /home/lsm/OpenCheetah/build/include/
是因为 `emp-ot` 并没有安装成功。
* 检查 `deps/emp-ot` 是不是空。
* 重跑 `bash scripts/build-deps.sh` 试试。

**Comment by lsm000** [comment]
您好，我的deps/emp-ot & deps/emp-tool都不是空的。我重新运行bash scripts/build-deps.sh后，出现和上面同样的错误，所有的错误提示都相同。

不过我这次又仔细看了一下，我开头的错误提示里写的：
-- Build files have been written to: /home/lsm/OpenCheetah/deps/emp-tool
make: *** 没有规则可制作目标“install”。 停止。
HEAD 目前位于 7f3d4f0 fix the bug #67 raised by @themighty1 (#68)
CMake Error at CMakeLists.txt:6 (include):
include could not find load file:
`CMAKE_FOLDER-NOTFOUND/cmake/emp-base.cmake`

但是根据CMakeLists.txt的第六行代码，我去OpenCheetah/deps/emp-tool/cmake/文件夹里看了，里面是包含emp-base.cmake文件的，而且有内容不为空。不知道为什么错误提示找不到文件。

**Comment by fionser** [comment]
我这边无法复现这个 error.
但是 emp-tool & emp-ot 都是 header-only 的。其实就是把他们 install 到 build/ 下面去就可以的。

**Comment by lsm000** [comment]
您好，我修改文件路径后还是没有成功，尝试了很多方法，最后重新安了一个新虚拟机，然后重新下载并安装，结果就可以跑通了，很神奇。

**Comment by HelmetOff** [comment]
您好，我是windows环境下用git bash尝试build dependencies。报了一样的错，该如何解决呢？
