### ISSUE TITLE
在运行demo时，卡在using silent ot pack

### ISSUE THREAD

**Issue by ryeosa** [Alibaba-Gemini-Lab/OpenCheetah#40]
如果是运行SCI_HE，就卡在using kkot pack，卡个十多分钟没有下一步进展

**Comment by fionser** [comment]
问 EzPC 吧；我们没修改任何 SCI HE的代码

**Comment by PingYi-226** [comment]
你好，我也遇到了你说的这个“卡在 using kkot pack”的类似问题，两边好像都在等待接收recv_data_internal()，然后就尬住了。
想请教一下你当时是怎么解决的？有做什么修改或配置上的调整吗？
万分感谢！

**Comment by fionser** [comment]
一般是有的地方没有 io->flush

**Comment by PingYi-226** [comment]
你好，我按照你的建议将setvbuf中的缓冲模式从_IOFBF改为了_IONBF，而且在send_data_internal()最后调用了fflush(stream)，还添加了一些输出，结果显示，两者前面的数据块都能正常交互，但是到了最后的1byte就收不到了。
下面是对齐后的输出，方便您查看
client: sending 32 bytes         | server: expecting 32 bytes
client: sent 32 bytes               | server: received 32 bytes
client: sending 32 bytes         | server: expecting 32 bytes
client: sent 32 bytes               | server: received 32 bytes
client: sending 16 bytes         | server: expecting 16 bytes
client: sent 16 bytes               | server: received 16 bytes
client: sending 16 bytes         | server: expecting 16 bytes
client: sent 16 bytes               | server: received 16 bytes
client: expecting 1 bytes        | server: sending 1 bytes
                                               | server: sent 1 bytes
                                               | server: expecting 1 bytes
请问这大概是哪方面的问题呢？非常感谢！
