### ISSUE TITLE
cmake出现问题

### ISSUE THREAD

**Issue by HolyFirstHub** [Alibaba-Gemini-Lab/OpenCheetah#6]
cmake时egine3.3.3.3 包不存在是怎么回事？
![b8e9320f3e3440d6b919777c9d46fc5](https://user-images.githubusercontent.com/93117166/165914992-10c70495-2f36-4f00-a721-6c20adbbaea9.jpg)

**Comment by zhifeng110** [comment]
检查OpenCheetah/build/deps/eigen目录下是否有Eigen3Config.cmake这个文件呢？

**Comment by zhifeng110** [comment]
看看deps/eigen目录下是否为空，空的话你clone就存在问题了呀，估计是网不好了。。。
