### ISSUE TITLE
如何换一张图片进行预测

### ISSUE THREAD

**Issue by lsm000** [Alibaba-Gemini-Lab/OpenCheetah#7]
您好，我现在想使用resnet50对其他图片进行预测，请问该怎样修改程序的输入？

**Comment by fionser** [comment]
可以参考 SqueezeNet 的 demo https://github.com/Alibaba-Gemini-Lab/OpenCheetah/tree/main/sqnet_demo
ResNet50的图片需要比较复杂的 预处理（如 bounding box 裁剪）。原 CrytoFlow2 库那边有提供相应的脚本，可以参考他们的做法。
