### ISSUE TITLE
test_ring_aux_protocols.cpp无法运行

### ISSUE THREAD

**Issue by zhifeng110** [Alibaba-Gemini-Lab/OpenCheetah#8]
尊敬的大佬：
       我在测试哈曼尔内积demo的时候又又又遇到了段错误，是因为Slient OT 暂且不支持吗？
![图片](https://user-images.githubusercontent.com/38159898/165968721-c8074665-da5e-470e-ae96-920cc41fe6ba.png)

**Comment by fionser** [comment]
test_hadamard_product ? test_ring_aux_protocols ?

LinearOT 的SilentOT 版本是没有实测过的。不保证能work。

**Comment by fionser** [comment]
test_hadamard_product ? test_ring_aux_protocols ?

LinearOT 的SilentOT 版本是没有实测过的。不保证能work。
